### ISSUE TITLE
How do I actually use this inside my project to generate migrations?

### ISSUE THREAD

**Issue by tabacitu** [GooGee/Entity-Builder#1]
I know I'm late to the party, but @GooGee , I think you've done some great work here. Congrats! I've been looking to build a good GUI to generate migrations for years! But never gotten to it. 

As opposed to others here, I do see a use case for it. When starting small/medium projects, I would actually prefer to have a GUI to define my database schema, rather than use Laracasts/Generators (what I do now), or manually write the migrations. I think it will be faster and more enjoyable - I often forget what migration columnType corresponds to which MySQL/PostgreSQL columnType. So I have to jump between the Laravel docs and the migration. Granted, this is a _minor_ inconvenience, but it _is_ something that causes frustration, and can be optimized. I bet many people feel the same.

I think it would also be helpful for Backpack for Laravel developers - currently we recommend people install Laracasts/Generators, which is the simple way to go about it, but... it doesn't generate relationships in Models, it doesn't generate Seeds, etc.

That being said, I'd love to use your package on a regular basis, or even recommend thousands of Backpack users install it, but I think there's one thing that's dragging it down: the documentation. People nowadays have a very short attention span. And I should know - I'm one of them :-) I've tried for 10-15 minutes to  wrap my head around the package, and understand how I can install and use it in my project, but I was unable to do so. So I quit. 

I think you need a few more paragraphs inside your README files, to help guide the user towards using the package in their project. To lead them towards the first moment the pacakage is useful to them. Some people call this an "AHA" moment - and they say _you need to take the user to that AHA moment ASAP - if you don't they'll quit_. That's exactly what happened to me.

Here's my user journey, I hope it will help you write a few more paragraphs to detail what the user should do, to get to that first moment that the software proves useful to them:
- I wanted to install the package in my project, and generate a migration;
- I browsed the original Github README, but it said I should install it with NPM; I said no, I'm looking for the PHP version;
- I found the PHP project, which is installable with Composer; I said "yay";
- I installed the PHP project, but there's no docs on how to use it;
- I browsed the source code, and found 4 routes;
- I accessed all the routes there, but I only got some JSON in return;
- I went to the original repo and it said I can use the online version; so I tried that one;
- I created a new project in the online version, but it looked like I couldn't choose custom column names - so I though it was just an online demo, not something I can use for my project, to then download the PHP files;
- then I quit; 
- then I spend _way too many minutes_ writing this post, to maybe help you :-)

It's entirely possible that I misread your docs. Or missed something in them. Of course. But again - this was _my_ user journey. And it's possible if I misread something, others will too.

Again, I would love a GUI for generating migrations. And I think you're on the right track. From the number of features alone it looks like you've worked on this A LOT, so I really appreciate it. But from developing public Github projects myself, and actually trying to use your software, my opinion is that - if you plan to work on this some more - your priority #1 should be better docs.

Just my 2 cents. I hope you take this the right way, I'm just trying to help. Let me know if you write a clear process on how I can use it to generate migrations - I'd love to take a second look.

Cheers!

**Comment by GooGee** [comment]
Sorry, I didn't make it clear.
1. Download the dist.zip of a released version
2. Unzip it to the public folder of your Laravel project
3. Visit localhost/index.html
