### ISSUE TITLE
Really good tool, however unable to connect to database

### ISSUE THREAD

**Issue by livinglegend13** [GooGee/Entity-Builder#16]
Trying to pull my hair through to understand how to database connection works. I am trying on both localhost as well as remote site. So my MySQL is running on 3306 and the Entity builder is asking me to enter the url information to connect. When I enter http://localhost it says network error or if I give with port information it gives me 404. What is the connection string. From the code it looks like its expecting JSON output from the connection. How will mysql will provide json output unless you use JDBC:mysql driver like connection string. Any help will be highly appreciated. Once again, great work with this tool.

**Comment by shabeebrizvi** [comment]
Simply follow the instruction: 

1. Download the dist.zip
2. Unzip it to the public folder of your Laravel project
3. Install the PHP package using `$ composer require googee/entity --dev`
4. Visit http://localhost/dist/index.html
5. Click 'Connect' button

**Comment by livinglegend13** [comment]
Never mind I found the answer. I am able to use this using code generator. Entity package does not work even after following the steps. Seems like they are two different package.

**Comment by shabeebrizvi** [comment]
> Never mind I found the answer. I am able to use this using code generator. Entity package does not work even after following the steps. Seems like they are two different package.

It works flawlessly as of today! 😊
