### ISSUE TITLE
Could this be adapted to Doctrine?

### ISSUE THREAD

**Issue by excitedbox** [GooGee/Entity-Builder#17]
Laravel and Symfony are built very similarly I was wondering if it is possible to make this work for symfony and doctrine?

**Comment by GooGee** [comment]
It is possible, but you have to do a lot of modifications, probably not worth it.

**Comment by excitedbox** [comment]
Actually I think it would. I have been looking for a tool like this and so have many others. The only visual option for Doctrine costs 300 EUROS :(
