### ISSUE TITLE
这是我见过最好的国产Laravel插件了！

### ISSUE THREAD

**Issue by hot588** [GooGee/Entity-Builder#3]
首先感谢群主贡献这样好的插件！

最早玩过一段时间！

我还添加过字段类型，Larvel已经支持枚举类型了，但是咱们就是没有！我看可以自定义类型了，觉得挺好，而且还能定义规则，都是很大的进步！

给您提个意见吧！

1、有了模型，不管是普通模型，还是API，都可以生成路由啊，路由也可以自动生成啊！ 希望下一个版本完善。

2、完善资源和资源类！ 我们没有这个功能！  写API的时候 ，资源和资源类是常用的东西！这个没有是不是不好啊！

希望您在下一个版本中完善！

**Comment by hot588** [comment]
看到了，有资源类！ 但是资源类 和模型之间的关联，能优化下就好了！

是控制器的路由，自动生成功能！

希望下一个版本，能有突破吧！

**Comment by GooGee** [comment]
这个版本已经可以做到了。

- 先在 `Layer` 页添加一个层
- 然后编写 `Template` 即可

如果需要其他业务层，也是这样做。
