### ISSUE TITLE
0 information

### ISSUE THREAD

**Issue by haykokalipsis** [GooGee/Entity-Builder#38]
Hi there. 
So first of all i am unable to connect to database. Whenever i click connect i get a popup asking for server. I input http://localhost or http://localhost/dist or http://localhost/dist/index.html and get "Request failed with status code 404"
I did everythinmg correctly: Downloaded and extracted dist, installed package and did EVERYTHING you described. 
Second problem is that when i create project and click download, i get a json file, not an archive. What am i supposed to do with it?
You have spent so much time creating this project and absolutely 0 second of explaining how to get it running. Make a full video of installation and usage. You will get much more love.

**Comment by GooGee** [comment]
1. make sure your local server is running
2. then click this http://localhost/dist/index.html
3. no need to change popup input

**Comment by haykokalipsis** [comment]
> 1. make sure your local server is running
> 2. then click this http://localhost/dist/index.html
> 3. no need to change popup input

I did with same result. Dude just make a video of SETUP and USAGE.

**Comment by haykokalipsis** [comment]
Also how do i Zip and download PHP code? when i create project and click download, i get a json file, not an archive.
