### ISSUE TITLE
Can you please explain the purpose?

### ISSUE THREAD

**Issue by lorvent** [GooGee/Entity-Builder#5]
Hello,

from looking at it, i can see this has lot of potential, but i am really not able to understand it properly.

can you please tell me what is the main purpose of it?

after downloading, i see that it is generating models and migration files,
is there anyway, generating views(blade files) aswell?

thanks,

**Comment by GooGee** [comment]
The purpose is to make coding easier.

See those doc in `Model`, it's generated automatically.

![model](https://raw.githubusercontent.com/GooGee/Entity-Builder/gh-pages/image/model.png)


## To generate views

1. make a new `Template`
2. make a new `Layer` called View
3. set View's template to the one made in step 1
4. go to `File` tab, you should see the `View`

**Comment by lorvent** [comment]
Thanks for the explanation,
i will try.

**Comment by romainlaisne** [comment]
Hi there,

I would like to comment that for me also it looks interesting but I also had trouble to understand the full potential of the code.

Perhaps an extra introduction in the README with a more verbose description would be helpful?

In the meantime I proceed exploring the potential of this ;)
