### ISSUE TITLE
有没有个使用介绍啊

### ISSUE THREAD

**Issue by yaoshiyizhu** [GooGee/Entity-Builder#7]
都不知道怎么用的，安装完成，有个介绍也好

**Comment by GooGee** [comment]
功能比较多，看起来有点复杂。但通常用不到那么多。
比较常用的 Tab ：
`Table` 设计数据表和索引
`Model` 模型关联和验证规则

![Tab](https://github.com/GooGee/Entity-Builder/raw/gh-pages/image/tab.png)
